MONGO_URL=process.env.MONGO_URL;
JWT_ADMIN_PASSWORD=process.env.JWT_ADMIN_PASSWORD;
JWT_USER_PASSWORD=process.env.JWT_USER_PASSWORD;
module.exports={
    MONGO_URL,
    JWT_ADMIN_PASSWORD,
    JWT_USER_PASSWORD
}
